<a href="https://colab.research.google.com/github/HN-UI/25_1_AI_DL/blob/main/practice_file/AI_DL_Week3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [3]:
from tensorflow import keras
from tensorflow.keras import layers
model = keras.Sequential([
    layers.Dense(512, activation="relu"),
    layers.Dense(10, activation="softmax")
])

In [4]:
# numpy.reshape
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255

In [5]:
model.compile(optimizer="rmsprop",
              loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])

In [6]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8752 - loss: 0.4344
Epoch 2/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9658 - loss: 0.1158
Epoch 3/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9793 - loss: 0.0721
Epoch 4/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9837 - loss: 0.0525
Epoch 5/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9898 - loss: 0.0361


---
## Element-wises Operations

In [7]:
def naive_relu(x):
    # 함수 input x가 2D 행렬인가?
    assert len(x.shape) == 2
    # x.copy()하고 x에 할당하였을 때, 함수 외부의 x (원본) 에는 영향을 주지 않음
    x = x.copy()
    # 2D 행렬의 각 원소들에 대해 relu function 수행
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] = max(x[i, j], 0)
    return x

In [8]:
def naive_add(x, y):
    # 함수 input x가 2D 행렬인가?
    assert len(x.shape) == 2
    # 함수의 input x와 y가 둘다 2D 행렬인가?
    assert x.shape == y.shape
    x = x.copy()
    # 원소별로 x 행렬에 y 행렬 값을 더하는 덧셈 연산 수행
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[i, j]
    return x

In [9]:
def naive_add_no_copy(x, y):
    # 함수 input x가 2D 행렬인가?
    assert len(x.shape) == 2
    # 함수의 input x와 y가 둘다 2D 행렬인가?
    assert x.shape == y.shape
    # 원소별로 x 행렬에 y 행렬 값을 더하는 덧셈 연산 수행
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[i, j]
    return x

In [10]:
import numpy as np
import time

# 0~1 사이 실수로 이루어진 (20, 100) 크기 행렬 생성
x = np.random.random((20, 100))
y = np.random.random((20, 100))

# 시작 시간을 기록
t0 = time.time()

# 1회 시행이 너무 빨라서 1000번 연산한 시간을 측정해야하므로 1000번 반복
for _ in range(1000):
    # numpy의 벡터화 연산
    z = x + y
    z = np.maximum(z, 0.)

# 종료 시간이 측정되며 출력
print("Took: {0:.2f} s".format(time.time() - t0))

Took: 0.01 s


In [11]:
# test about x.copy()

# 원본 x 출력
print(x)

# naive_add를 거친 z (x = x.copy() 연산 사용됨)
z = naive_add(x, y)

# z 출력
print(z)

# 원본 x 값이 z로 변경 되었는가? No
print(np.array_equal(x, z))

[[0.78856533 0.16225049 0.73736429 ... 0.07992938 0.4062229  0.92805893]
 [0.02054381 0.05240552 0.77142823 ... 0.06475143 0.47041185 0.46137219]
 [0.59964979 0.60337779 0.93785249 ... 0.47996145 0.66764601 0.20903809]
 ...
 [0.87383145 0.34550639 0.49238951 ... 0.03597472 0.82003695 0.03713511]
 [0.28500852 0.62985136 0.72804325 ... 0.67784796 0.11941653 0.69578879]
 [0.1271649  0.30886448 0.40845454 ... 0.49664577 0.8939915  0.66067624]]
[[1.08979773 0.41870505 1.28779603 ... 0.77989517 1.09060599 1.01107098]
 [0.2442643  0.18784759 1.56373797 ... 0.17155633 1.26770161 0.98109693]
 [1.04569379 1.28576524 1.20110328 ... 1.02781026 1.06209649 1.15473541]
 ...
 [1.12189331 1.28737849 0.49755224 ... 0.24430713 1.22124802 0.5634019 ]
 [1.2619055  1.25689414 1.52889058 ... 1.16004762 0.54110306 0.82972429]
 [0.43374409 0.65900925 1.03761052 ... 1.37628235 0.96779266 0.96025866]]
False


In [12]:
# test about x.copy()

# 원본 x 출력
print(x)

# naive_add_no_copy를 거친 z (x = x.copy() 연산 사용하지 않는 함수)
z = naive_add_no_copy(x, y)

# z 출력
print(z)

# 원본 x 값이 z로 변경 되었는가? Yes
print(np.array_equal(x, z))

[[0.78856533 0.16225049 0.73736429 ... 0.07992938 0.4062229  0.92805893]
 [0.02054381 0.05240552 0.77142823 ... 0.06475143 0.47041185 0.46137219]
 [0.59964979 0.60337779 0.93785249 ... 0.47996145 0.66764601 0.20903809]
 ...
 [0.87383145 0.34550639 0.49238951 ... 0.03597472 0.82003695 0.03713511]
 [0.28500852 0.62985136 0.72804325 ... 0.67784796 0.11941653 0.69578879]
 [0.1271649  0.30886448 0.40845454 ... 0.49664577 0.8939915  0.66067624]]
[[1.08979773 0.41870505 1.28779603 ... 0.77989517 1.09060599 1.01107098]
 [0.2442643  0.18784759 1.56373797 ... 0.17155633 1.26770161 0.98109693]
 [1.04569379 1.28576524 1.20110328 ... 1.02781026 1.06209649 1.15473541]
 ...
 [1.12189331 1.28737849 0.49755224 ... 0.24430713 1.22124802 0.5634019 ]
 [1.2619055  1.25689414 1.52889058 ... 1.16004762 0.54110306 0.82972429]
 [0.43374409 0.65900925 1.03761052 ... 1.37628235 0.96779266 0.96025866]]
True


In [13]:
t0 = time.time()
for _ in range(1000):
    z = naive_add(x, y)
    z = naive_relu(z)
print("Took: {0:.2f} s".format(time.time() - t0))

Took: 3.18 s


---
## Broadcasting

In [14]:
X = np.random.random((32, 10))
y = np.random.random((10,))

In [15]:
y = np.expand_dims(y, axis=0)

In [16]:
Y = np.concatenate([y] * 32, axis=0)

In [17]:
def naive_add_matrix_and_vector(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[j]
    return x

In [18]:
x = np.random.random((64, 3, 32, 10))
y = np.random.random((32, 10))
z = np.maximum(x, y)

---
## Gradient-based Optimization

In [19]:
import tensorflow as tf

x = tf.Variable(2.0)
y = tf.Variable(1.0)
with tf.GradientTape() as tape:
    d = pow(x, 2) * y + x * y + 3 * y
grad_of_y_wrt_x = tape.gradient(d, [x, y])
print(grad_of_y_wrt_x)

[<tf.Tensor: shape=(), dtype=float32, numpy=5.0>, <tf.Tensor: shape=(), dtype=float32, numpy=9.0>]


In [21]:
x = tf.constant(np.array([1.,4.,3.]).reshape(1, 3), dtype = tf.float32)
b = tf.Variable(tf.zeros((2,)), dtype = tf.float32)
W = tf.Variable(tf.random.uniform((3, 2)), dtype=tf.float32)

In [25]:
with tf.GradientTape() as tape:
    f1 = tf.matmul(x, W) + b

grad_W, grad_b = tape.gradient(f1, [W, b])
print(grad_W)
print(grad_b)

tf.Tensor(
[[1. 1.]
 [4. 4.]
 [3. 3.]], shape=(3, 2), dtype=float32)
tf.Tensor([1. 1.], shape=(2,), dtype=float32)


In [26]:
with tf.GradientTape() as tape:
    f2 = tf.pow(tf.matmul(x, W) + b, 3)

grad_W, grad_b = tape.gradient(f2, [W, b])

print(grad_W)
print(grad_b)

tf.Tensor(
[[ 62.7025   104.684235]
 [250.81     418.73694 ]
 [188.1075   314.0527  ]], shape=(3, 2), dtype=float32)
tf.Tensor([ 62.7025   104.684235], shape=(2,), dtype=float32)
